# Generated by Django 4.1.6 on 2023-02-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=400)),
                ('content', models.CharField(max_length=800)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsarticle.author')),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=100)),
                ('technology', models.CharField(max_length=100)),
                ('entertainment', models.CharField(max_length=100)),
                ('generalNews', models.CharField(max_length=100)),
                ('historicalNews', models.CharField(max_length=100)),
                ('healthAndMedicine', models.CharField(max_length=100)),
                ('lifestyle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticleCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsArticleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsarticle.newsarticle')),
                ('newsCategoriesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsarticle.newscategory')),
            ],
        ),
    ]
